map super+shift+, load_config_file

map super+c copy_to_clipboard
map super+v paste_from_clipboard

map super+n launch --location=split
map super+shift+n launch --location=split --cwd=current
map super+q close_window

map super+l neighboring_window right
map super+h neighboring_window left
map super+j neighboring_window down
map super+k neighboring_window up

map super+f toggle_layout_stack
