font_size        12.0
background_opacity 0.8
background_blur    20
inactive_text_alpha 0.3
inactive_tab_background #000000

window_border_width 1pt
active_border_color #00ff00

start_as_fullscreen    yes
hide_window_decorations yes

macos_titlebar_color               system
macos_option_as_alt                yes
macos_quit_when_last_window_closed yes
macos_show_window_title_in         none

tab_bar_edge top
tab_bar_min_tabs 2
tab_bar_style separator
tab_separator " "

input_delay 0
repaint_delay 1
sync_to_monitor yes


include mocha.conf
